### ISSUE TITLE
 支持中文 Support Chinese

### ISSUE THREAD

**Issue by zengleyi** [jaames/zfont#5]
支持中文 Support Chinese, i want

**Comment by jaames** [comment]
You can use Chinese text if you provide a .ttf font that contains Chinese characters, such as [these ones](https://cooltext.com/Fonts-Unicode-Chinese)

<img width="571" alt="Screenshot 2019-10-26 at 11 14 03" src="https://user-images.githubusercontent.com/9112876/67618061-bb161680-f7e1-11e9-9ddc-d2c5f297c523.png">

**Comment by zengleyi** [comment]
thank you @jaames
