### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by demensky** [jaames/zfont#6]
[@types/zdog](https://www.npmjs.com/package/@types/zdog) already exists. Let's make definitions (@types/zfont) for this package?

**Comment by jaames** [comment]
A PR would be welcome if somebody else would like to start on it! I don't much free time right now :)

**Comment by demensky** [comment]
Done. But I still do not understand what is the benefit of using the [`init`](https://github.com/jaames/zfont/blob/367627f845d3f2bf82a46afb0bb632441e826e90/src/index.js#L6) function. What are the benefits compared to regular `export`?
