### ISSUE TITLE
Source map not present in CDN

### ISSUE THREAD

**Issue by sebinsuresh** [jaames/zfont#9]
Chrome browser complains about a missing source map when using the jsDelivr CDN to load the script.
![image](https://user-images.githubusercontent.com/30849879/120245942-6bf15c80-c234-11eb-9b58-f1d41d5e84f3.png)

**Comment by jaames** [comment]
This isn't really an issue unless you really need to debug the library for some reason, in which case you can just grab the necessary files from this repo instead.
